before:
  hooks:
    - go test ./...

builds:
  - id: signable
    mod_timestamp: '{{ .CommitTimestamp }}'
    targets:
      - darwin_amd64
      - windows_386
      - windows_amd64
    hooks:
      post: |
        docker run
          -e ARTIFACTORY_TOKEN={{ .Env.ARTIFACTORY_TOKEN }}
          -e ARTIFACTORY_USER={{ .Env.ARTIFACTORY_USER }}
          -e CIRCLE_TOKEN={{ .Env.CIRCLE_TOKEN }}
          -v {{ dir .Path }}:/workdir
          {{ .Env.CODESIGN_IMAGE }}
          sign -product-name={{ .ProjectName }} {{ .Name }}
    dir: ./cmd/inclusify/
    flags:
      - -trimpath
    ldflags:
      - '-X "main.GitCommit=$(shell git rev-parse HEAD)"'
  - mod_timestamp: '{{ .CommitTimestamp }}'
    targets:
      - linux_386
      - linux_amd64
    dir: ./cmd/inclusify/
    flags:
      - -trimpath
    ldflags:
      - '-X "main.GitCommit=$(shell git rev-parse HEAD)"'

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files: 
      - none*

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - args: ["-u", "{{ .Env.PGP_KEY_ID }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
    artifacts: checksum
 
publishers:
  - name: "hc-releases"
    checksum: true
    signature: true
    cmd: hc-releases upload-file {{ abs .ArtifactPath }} --bucket {{ .Env.RELEASES_AWS_BUCKET }}
    env:
      - AWS_ACCESS_KEY_ID={{ .Env.RELEASE_AWS_ACCESS_KEY_ID }}
      - AWS_SECRET_ACCESS_KEY={{ .Env.RELEASE_AWS_SECRET_ACCESS_KEY }}
      - RELEASES_AWS_BUCKET={{ .Env.RELEASES_AWS_BUCKET }}

changelog:
  skip: true
