name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Install hc-codesign
        id: codesign
        run: |
          docker login docker.pkg.github.com -u docker -p $GITHUB_TOKEN && \
          docker pull docker.pkg.github.com/hashicorp/hc-codesign/hc-codesign:$VERSION && \
          echo "::set-output name=image::docker.pkg.github.com/hashicorp/hc-codesign/hc-codesign:$VERSION"
        env:
          VERSION: v0
          GITHUB_TOKEN: ${{ secrets.CODESIGN_GITHUB_TOKEN }}
      - name: Install hc-releases
        run: |
          DOWNLOAD_URL=$(curl -SsL \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/hashicorp/hc-releases/releases/latest \
            | jq -r '.assets[] | select(.name | contains("linux_amd64.tgz")) | .url')
          curl -SsL -o /tmp/hc-releases.tgz \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/octet-stream" ${DOWNLOAD_URL}
          tar xzf /tmp/hc-releases.tgz
          sudo mv hc-releases /usr/bin/hc-releases
          hc-releases version
        env: 
          GITHUB_TOKEN: ${{ secrets.CODESIGN_GITHUB_TOKEN }}
      - name: Install wget & clamAV antivirus scanner
        run : |
           sudo apt-get -qq install -y ca-certificates wget clamav
           wget --version
      - name: Install maldet malware scanner
        run: |
          wget --no-verbose -O maldet-$VERSION.tar.gz https://github.com/rfxn/linux-malware-detect/archive/$VERSION.tar.gz
          sha256sum -c - <<< "$SHA256SUM  maldet-$VERSION.tar.gz"
          sudo mkdir -p maldet-$VERSION
          sudo tar -xzf maldet-$VERSION.tar.gz --strip-components=1 -C maldet-$VERSION
          cd maldet-$VERSION
          sudo ./install.sh
          sudo maldet -u
        env: 
          VERSION: 1.6.4
          SHA256SUM: 3ad66eebd443d32dd6c811dcf2d264b78678c75ed1d40c15434180d4453e60d2
      - name: Import PGP key for archive signing
        run: echo -e "$PGP_KEY" | gpg --import
        env:
          PGP_KEY: ${{ secrets.PGP_SIGNING_KEY }}
      - name: GitHub Release
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release
        env:
          PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
          CODESIGN_IMAGE: ${{ steps.codesign.outputs.image }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
          RELEASES_AWS_BUCKET: ${{ secrets.RELEASES_AWS_BUCKET }}
      - name: Run clamAV antivirus scanner
        run: sudo clamscan /home/runner/work/$REPO/$REPO/dist/
        env:
          REPO: ${{ github.event.repository.name }}
      - name: Run maldet malware scanner
        run: sudo maldet -a /home/runner/work/$REPO/$REPO/dist/
        env:
          REPO: ${{ github.event.repository.name }}
      - name: Publish released artifacts in the staging S3 bucket
        run: hc-releases publish --bucket=$RELEASES_AWS_BUCKET
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.RELEASE_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.RELEASE_AWS_SECRET_ACCESS_KEY }}
          FASTLY_API_TOKEN: ${{ secrets.RELEASE_FASTLY_API_TOKEN }}
          RELEASES_AWS_BUCKET: ${{ secrets.RELEASES_AWS_BUCKET }}
          REPO: ${{ github.event.repository.name }}
