### This runs GitHub's static analysis engine, CodeQL, against the repo's source code 
### to find security vulnerabilities. It then automatically uploads the results
### to GitHub so they can be displayed in the repo's security tab. 
### Source: https://github.com/github/codeql-action

name: Code Scanning

on:
  - push
  - pull_request

jobs: 
  scanning:
    name: CodeQL Scanning
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    # If this run was triggered by a pull request event, then checkout
    # the head of the pull request instead of the merge commit
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java)
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
  